//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 09:04:29 AM CDT 
//


package com.jamfsoftware.research.macingestor.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}string"/>
 *         &lt;element ref="{}stringArray"/>
 *         &lt;element ref="{}integer"/>
 *         &lt;element ref="{}integerArray"/>
 *         &lt;element ref="{}float"/>
 *         &lt;element ref="{}floatArray"/>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}boolean"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stringOrStringArrayOrInteger"
})
@XmlRootElement(name = "dict")
public class Dict {

    @XmlElements({
        @XmlElement(name = "string", type = String.class),
        @XmlElement(name = "stringArray", type = StringArray.class),
        @XmlElement(name = "integer", type = Integer.class),
        @XmlElement(name = "integerArray", type = IntegerArray.class),
        @XmlElement(name = "float", type = Float.class),
        @XmlElement(name = "floatArray", type = FloatArray.class),
        @XmlElement(name = "date", type = Date.class),
        @XmlElement(name = "boolean", type = Boolean.class)
    })
    protected List<Object> stringOrStringArrayOrInteger;

    /**
     * Gets the value of the stringOrStringArrayOrInteger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringOrStringArrayOrInteger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringOrStringArrayOrInteger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link StringArray }
     * {@link Integer }
     * {@link IntegerArray }
     * {@link Float }
     * {@link FloatArray }
     * {@link Date }
     * {@link Boolean }
     * 
     * 
     */
    public List<Object> getStringOrStringArrayOrInteger() {
        if (stringOrStringArrayOrInteger == null) {
            stringOrStringArrayOrInteger = new ArrayList<Object>();
        }
        return this.stringOrStringArrayOrInteger;
    }

}
