//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 09:04:29 AM CDT 
//


package com.jamfsoftware.research.macingestor.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jamfsoftware.research.macingestor.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BundleId_QNAME = new QName("", "bundleId");
    private final static QName _Version_QNAME = new QName("", "version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jamfsoftware.research.macingestor.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FieldGroup }
     * 
     */
    public FieldGroup createFieldGroup() {
        return new FieldGroup();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link FloatConstraintType }
     * 
     */
    public FloatConstraintType createFloatConstraintType() {
        return new FloatConstraintType();
    }

    /**
     * Create an instance of {@link IntegerConstraintType }
     * 
     */
    public IntegerConstraintType createIntegerConstraintType() {
        return new IntegerConstraintType();
    }

    /**
     * Create an instance of {@link StringConstraintType }
     * 
     */
    public StringConstraintType createStringConstraintType() {
        return new StringConstraintType();
    }

    /**
     * Create an instance of {@link FloatArrayConstraintType }
     * 
     */
    public FloatArrayConstraintType createFloatArrayConstraintType() {
        return new FloatArrayConstraintType();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link DateValueType }
     * 
     */
    public DateValueType createDateValueType() {
        return new DateValueType();
    }

    /**
     * Create an instance of {@link DateConstraintType }
     * 
     */
    public DateConstraintType createDateConstraintType() {
        return new DateConstraintType();
    }

    /**
     * Create an instance of {@link FloatArray }
     * 
     */
    public FloatArray createFloatArray() {
        return new FloatArray();
    }

    /**
     * Create an instance of {@link FloatArrayValueType }
     * 
     */
    public FloatArrayValueType createFloatArrayValueType() {
        return new FloatArrayValueType();
    }

    /**
     * Create an instance of {@link com.jamfsoftware.research.macingestor.jaxb.String }
     * 
     */
    public com.jamfsoftware.research.macingestor.jaxb.String createString() {
        return new com.jamfsoftware.research.macingestor.jaxb.String();
    }

    /**
     * Create an instance of {@link StringValueType }
     * 
     */
    public StringValueType createStringValueType() {
        return new StringValueType();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link com.jamfsoftware.research.macingestor.jaxb.Integer }
     * 
     */
    public com.jamfsoftware.research.macingestor.jaxb.Integer createInteger() {
        return new com.jamfsoftware.research.macingestor.jaxb.Integer();
    }

    /**
     * Create an instance of {@link IntegerValueType }
     * 
     */
    public IntegerValueType createIntegerValueType() {
        return new IntegerValueType();
    }

    /**
     * Create an instance of {@link FieldGroup.Name }
     * 
     */
    public FieldGroup.Name createFieldGroupName() {
        return new FieldGroup.Name();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Options.Option }
     * 
     */
    public Options.Option createOptionsOption() {
        return new Options.Option();
    }

    /**
     * Create an instance of {@link Float }
     * 
     */
    public Float createFloat() {
        return new Float();
    }

    /**
     * Create an instance of {@link FloatValueType }
     * 
     */
    public FloatValueType createFloatValueType() {
        return new FloatValueType();
    }

    /**
     * Create an instance of {@link Presentation }
     * 
     */
    public Presentation createPresentation() {
        return new Presentation();
    }

    /**
     * Create an instance of {@link IntegerArray }
     * 
     */
    public IntegerArray createIntegerArray() {
        return new IntegerArray();
    }

    /**
     * Create an instance of {@link IntegerArrayValueType }
     * 
     */
    public IntegerArrayValueType createIntegerArrayValueType() {
        return new IntegerArrayValueType();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link BooleanValueType }
     * 
     */
    public BooleanValueType createBooleanValueType() {
        return new BooleanValueType();
    }

    /**
     * Create an instance of {@link BooleanConstraintType }
     * 
     */
    public BooleanConstraintType createBooleanConstraintType() {
        return new BooleanConstraintType();
    }

    /**
     * Create an instance of {@link UserVariable }
     * 
     */
    public UserVariable createUserVariable() {
        return new UserVariable();
    }

    /**
     * Create an instance of {@link Dict }
     * 
     */
    public Dict createDict() {
        return new Dict();
    }

    /**
     * Create an instance of {@link StringArray }
     * 
     */
    public StringArray createStringArray() {
        return new StringArray();
    }

    /**
     * Create an instance of {@link StringArrayValueType }
     * 
     */
    public StringArrayValueType createStringArrayValueType() {
        return new StringArrayValueType();
    }

    /**
     * Create an instance of {@link ManagedAppConfiguration }
     * 
     */
    public ManagedAppConfiguration createManagedAppConfiguration() {
        return new ManagedAppConfiguration();
    }

    /**
     * Create an instance of {@link DeviceVariable }
     * 
     */
    public DeviceVariable createDeviceVariable() {
        return new DeviceVariable();
    }

    /**
     * Create an instance of {@link FloatConstraintType.Values }
     * 
     */
    public FloatConstraintType.Values createFloatConstraintTypeValues() {
        return new FloatConstraintType.Values();
    }

    /**
     * Create an instance of {@link IntegerConstraintType.Values }
     * 
     */
    public IntegerConstraintType.Values createIntegerConstraintTypeValues() {
        return new IntegerConstraintType.Values();
    }

    /**
     * Create an instance of {@link StringConstraintType.Values }
     * 
     */
    public StringConstraintType.Values createStringConstraintTypeValues() {
        return new StringConstraintType.Values();
    }

    /**
     * Create an instance of {@link FloatArrayConstraintType.Values }
     * 
     */
    public FloatArrayConstraintType.Values createFloatArrayConstraintTypeValues() {
        return new FloatArrayConstraintType.Values();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bundleId")
    public JAXBElement<java.lang.String> createBundleId(java.lang.String value) {
        return new JAXBElement<java.lang.String>(_BundleId_QNAME, java.lang.String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<java.lang.Integer> createVersion(java.lang.Integer value) {
        return new JAXBElement<java.lang.Integer>(_Version_QNAME, java.lang.Integer.class, null, value);
    }

}
