//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 09:04:29 AM CDT 
//


package com.jamfsoftware.research.macingestor.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stringArrayValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stringArrayValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}userVariable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}deviceVariable" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stringArrayValueType", propOrder = {
    "valueOrUserVariableOrDeviceVariable"
})
public class StringArrayValueType {

    @XmlElements({
        @XmlElement(name = "value", type = java.lang.String.class),
        @XmlElement(name = "userVariable", type = UserVariable.class),
        @XmlElement(name = "deviceVariable", type = DeviceVariable.class)
    })
    protected List<Object> valueOrUserVariableOrDeviceVariable;

    /**
     * Gets the value of the valueOrUserVariableOrDeviceVariable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueOrUserVariableOrDeviceVariable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueOrUserVariableOrDeviceVariable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * {@link UserVariable }
     * {@link DeviceVariable }
     * 
     * 
     */
    public List<Object> getValueOrUserVariableOrDeviceVariable() {
        if (valueOrUserVariableOrDeviceVariable == null) {
            valueOrUserVariableOrDeviceVariable = new ArrayList<Object>();
        }
        return this.valueOrUserVariableOrDeviceVariable;
    }

}
